version: '3'

services:

  nginx:
    build: ./nginx
    ports:
      - 8888:80
    volumes:
      - ./app:/var/www/html

  php:
    build: ./php
    volumes:
      - ./app:/var/www/html

  varnish:
    build: ./varnish
    ports:
      - 80:80
